cvm-version: 0.10.4
cpus: 2
memory: 8192
networks:
  web:
    egress: open
containers:
  - name: "whoami"
    image: "traefik/whoami@sha256:200689790a0a0ea48ca45992e0450bc26ccab5307375b41c84dfc4f2475937ab"
    restart: always
    networks: [web]
shim:
  upstream-port: 80
  paths:
    - "/"
